# Arithmatic Operations

 # 1. Add Operation

In [4]:
import numpy as np 
arr_1 = np.array([[1,2,3,4],[5,6,4,9]])
arr_1_new = arr_1 + 3
print(arr_1_new)
print(arr_1.ndim)

[[ 4  5  6  7]
 [ 8  9  7 12]]
2


In [5]:
arr_1 = np.array([[1,2,3,4],[5,6,4,9]])
arr_2 = np.array([[5,7,6,4],[1,5,45,6]])
arr_new = arr_1 + arr_2
print(arr_new)
print(arr_new.ndim)

[[ 6  9  9  8]
 [ 6 11 49 15]]
2


In [6]:
arr_1 = np.array([[1,2,3,4],[5,6,4,9]])
mul= arr_1 * 3
print(mul)

[[ 3  6  9 12]
 [15 18 12 27]]


In [10]:
arr_1 = np.array([[1,2,3,4],[5,6,4,9]])
arr_2 = np.array([[5,7,6,4],[1,5,45,6]])
arr_new = arr_1 * arr_2
print(arr_new)

[[  5  14  18  16]
 [  5  30 180  54]]


In [11]:
# Define two 2D matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
result = np.matmul(matrix_a, matrix_b)

print(result)

[[19 22]
 [43 50]]
