# Arithmetic Function

In [18]:
import numpy as np
arr = np.array([1,2,3,8,5,4])
print("min: ",np.min(arr), np.argmin(arr))   # to get the minimum value from the array. argmin--> to get the index at where it is present
print("max: ",np.max(arr), np.argmax(arr))   #to get the maximum value from the array. argmin--> to get the index at where it is present

min:  1 0
max:  8 3


In [16]:
var_1 = np.array([[2,3,5],[7,9,3]])
print(np.min(var_1, axis=1))  # axis=1 for row
print(np.min(var_1, axis=0)) # axis=0 for column


[2 3]
[2 3 3]


In [17]:
# sqrt() for squareroot 
var_2 = np.array([1,2,3,8,5,4])
print(np.sqrt(var_2))

[1.         1.41421356 1.73205081 2.82842712 2.23606798 2.        ]


In [19]:
# sin() for sine value of matrix
var_2 = np.array([1,2,3,8,5,4])
print(np.sin(var_2))

[ 0.84147098  0.90929743  0.14112001  0.98935825 -0.95892427 -0.7568025 ]


In [20]:
# cos() for sine value of matrix
var_2 = np.array([1,2,3,8,5,4])
print(np.cos(var_2))

[ 0.54030231 -0.41614684 -0.9899925  -0.14550003  0.28366219 -0.65364362]


In [21]:
# cumsum() for sine value of matrix
var_2 = np.array([1,2,3,8,5,4])
print(np.cumsum(var_2)) # cumsum is a function like 1+2=3, 3+3=6, 6+8=14,.....

[ 1  3  6 14 19 23]
