# 1.  ARRAY

In [6]:
import numpy as np 
arr=[1,2,3,4]
y=np.array(arr)
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


   USER INPUT IN ARRAY

In [10]:
l=[]
for i in range(1,6):
    array_1=int(input("enter elements: "))
    l.append(array_1)
array_2=np.array(l)
print(np.array(array_2))
print(array_2.ndim)

enter elements:  1
enter elements:  2
enter elements:  3
enter elements:  4
enter elements:  5


[1 2 3 4 5]
1


# 2. 2-Dimensional array 

In [11]:
array_1=np.array([[1,2,3,4,5]])
print(array_1)
print(array_1.ndim)

[[1 2 3 4 5]]
2


In [12]:
ar2=np.array([[1,2,3,4],[5,6,7,8]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


3. 3-Dimensional Array 

In [13]:
ar3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


# 3.  Conversion to multi dimensional array

ndim 
ndmin

In [24]:
import numpy as np
array_5=np.array([1,2,3,5,8],ndmin=10) # ALERT IT IS 'ndmin' not 'ndim'
print(array_5)
print(array_5.ndim)

[[[[[[[[[[1 2 3 5 8]]]]]]]]]]
10


# zero's arrays

In [27]:
import numpy as np
arr_zero=np.zeros(4)
print(arr_zero)

[0. 0. 0. 0.]


In [28]:
arra=np.zeros((3,4)) # multi-dimentional array in zero array form
print(arra)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones 

In [31]:
arra_1=np.ones(4)
print(arra_1)
print(arra_1.ndim)
print()
arra_12=np.ones((2,4))
print(arra_12)

[1. 1. 1. 1.]
1

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# empty 

In [32]:
ar_emp=np.empty(4)
print(ar_emp)

[1. 1. 1. 1.]


# RANGE 

In [36]:
ar_range=np.arange(4)
print(ar_range)

[0 1 2 3]


# DIAGONAL

In [37]:
ar_dia= np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
 
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# linspace

In [43]:
ar_lin=np.linspace(2,20,num=4)
print(ar_lin)

[ 2.  8. 14. 20.]
