# RANDOM

 # 1. rand() ( to create random number from 0 to 1)

In [1]:
import numpy as np
var = np.random.rand(4)
print(var)

[0.62231418 0.03134494 0.63337924 0.67866247]


In [2]:
var_2 = np.random.rand(2,3)
print(var_2)


[[0.13622826 0.40657804 0.99458339]
 [0.28234622 0.25160267 0.80748247]]


# 2. randn() (to create random number close to zero it can be positive or nagetive)

In [3]:
var_3 = np.random.randn(4)
print(var_3)

[ 0.34174538 -1.66307801 -1.05515111 -0.38478752]


# 3. ranf() (to generate random float numbers from 0.0 --> 1.0(tends to 1))

In [5]:
var4 = np.random.ranf(4)
print(var4)

[0.11321538 0.77071704 0.66366415 0.32243493]


# 4. randint() (to generate random number to given range)

In [10]:
var5 = np.random.randint(1,9,(4,5)) # (min=1, max=9,(row=4,column=5))
print(var5)

[[3 5 7 7 8]
 [2 2 1 3 6]
 [4 8 1 8 8]
 [8 5 4 4 8]]
