In [4]:
import numpy as np
var_1 = np.array([1,2,3,4])
var_2 = np.array([1,2,3,4])
print(var_1 + var_2)


[2 4 6 8]


In [7]:
var_3 = np.array([1,2,3])
var_4 = np.array([[1],[2],[3]])
print(var_3 * var_4)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [11]:
x = np.array([[1],[2],[3]])
print(x.shape)
var_5 = np.array([[1,2,3],[1,2,3],[1,2,3]])
print(var_5.shape)
print(x * var_5)
print()

print(x + var_5)



(3, 1)
(3, 3)
[[1 2 3]
 [2 4 6]
 [3 6 9]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]
