In [4]:
import numpy as  np
var1 = np.array([1])
print("Data type: ", var1.dtype)

Data type:  int64


In [6]:
var2 = np.array([1.0,2.1,3.5])
print(type(var2), var2.dtype)

<class 'numpy.ndarray'> float64


In [7]:
var2 = np.array(["s","S","y"])
print(type(var2), var2.dtype) # string data type is 'U1'

<class 'numpy.ndarray'> <U1


In [10]:
var2 = np.array(["s","S","y",'d',1,5,6,5])
print(type(var2), var2.dtype) # string data type is 'U21'

<class 'numpy.ndarray'> <U21


In [18]:
x = np.array([1,2,3,25], dtype = np.int8)
print(x.dtype)  


int8


In [23]:
x = np.array([1,2,3,25], dtype = "f") # convertion of data-type using short-cut characters
print(x.dtype)
print(x)


float32
[ 1.  2.  3. 25.]


In [27]:
x = np.array([1,2,3,25]) 
print(x.dtype)
print(x)
new = np.float64(x)
print(new.dtype)
print(new)


int64
[ 1  2  3 25]
float64
[ 1.  2.  3. 25.]
