# search

In [4]:
import numpy as np
var = np.array([1,2,3,4,5,6,4,5,2,3,2])
print(np.where(var==2))
               

(array([ 1,  8, 10], dtype=int64),)


In [6]:
var1 = np.array([1,2,3,4,6,7])
print(np.searchsorted(var1,5))

4


# sort

In [10]:
var3 = np.array([4,64,62,654,497,662,484,23,25484,66,4612,6255,92323,64,412121])
print(np.sort(var3))

[     4     23     62     64     64     66    484    497    654    662
   4612   6255  25484  92323 412121]


# shuffle

In [20]:
var4 = np.array([1,2,3,4,5])
np.random.shuffle(var4)
print(var4)

[3 2 1 4 5]


# unique

In [17]:
var5 = np.array([1,2,3,2,5,6,5])
x11 = np.unique(var5,return_index=True)
print(x11)

(array([1, 2, 3, 5, 6]), array([0, 1, 2, 4, 5], dtype=int64))


# resize

In [25]:
var6 = np.array([1,2,3,4,5,6])
print(np.resize(var6,(3,2)))

[[1 2]
 [3 4]
 [5 6]]
