In [2]:
import numpy as np
x = np.array([1,2,3,4,5,6])
for i in x:
    print(i)

1
2
3
4
5
6


In [3]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
for k in var1:
    for l in k:
        print(l)

1
2
3
4
1
2
3
4


In [8]:
var2 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

for k in var2:
    for l in k:
        for s in l:
            print(s)

1
2
3
4
1
2
3
4
1
2
3
4


In [18]:
var3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

for k in np.nditer(var3):
    print(k)
print()
print(var3.ndim)
print(var3)

1
2
3
4
1
2
3
4
1
2
3
4

3
[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]


In [19]:
var4 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

for k in np.nditer(var4,flags=['buffered'],op_dtypes=["S"]):
    print(k)
print()
print(var3.ndim)
print(var3)

b'1'
b'2'
b'3'
b'4'
b'1'
b'2'
b'3'
b'4'
b'1'
b'2'
b'3'
b'4'

3
[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]


In [22]:
var3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
for i,n in np.ndenumerate(var3):
    print(i,n)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4
(0, 2, 0) 1
(0, 2, 1) 2
(0, 2, 2) 3
(0, 2, 3) 4
