# joining

In [1]:
import numpy as np 
var = np.array([1,2,3,4])
var1 = np.array([5,6,7,8])
ar = np.concatenate((var,var1))
print(ar)


[1 2 3 4 5 6 7 8]


In [2]:
var2 = np.array([[1,2],[3,4]])
var3 = np.array([[5,6],[7,8]])
ar1 = np.concatenate((var2,var3),axis=1)
print(ar1)

[[1 2 5 6]
 [3 4 7 8]]


In [18]:
import numpy as np

# Define the arrays
var_2 = np.array([[1, 2], [3, 4]])
var_3 = np.array([[5, 6], [7, 8]])

# Stack the arrays along a new axis
result = np.vstack((var_2, var_3))                # vstack uses to join the array in column form
print(result)
print()
print(np.hstack((var_2, var_3)))
print()
print(np.stack((var_2, var_3)))
print()
print(np.dstack((var_2, var_3)))



[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


# split 

In [22]:
a = np.array([1,2,3,4,5,6])
print(np.array_split(a,(3)))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [23]:
a1 = np.array([[1,2],[3,4],[5,6]])
print(np.array_split(a1,(3)))

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
