# Shape 

In [1]:
import numpy as np 

var = np.array([[1,2,3],[4,5,6]])
print()
print(var.shape)


(2, 3)


In [3]:
var_1 = np.array([1,2,3], ndmin=5)
print(var_1)
print(var_1.shape)
print(var_1.ndim)

[[[[[1 2 3]]]]]
(1, 1, 1, 1, 3)
5


# Reshape

In [6]:
var_2 = np.array([1,2,3,4,5,6])
x = var_2.reshape(2,3) 
print(x)
print(x.ndim)

[[1 2 3]
 [4 5 6]]
2


In [15]:
var_3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x1 = var_3.reshape(4,3)
print(x1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
